---
- name: Obtain CA cert
  uri:
    url: "https://{{ groups['masters'][0] }}/ca/dcos-ca.crt"
    method: GET
    status_code: 200
    validate_certs: no
    return_content: yes
  register: ca_cert

- name: Create a CA cert file
  copy:
    content: "{{ ca_cert.content }}"
    dest: "{{ cacert_destination_file }}"