---
- name: Obtain a token to authenticate
  shell: >
    curl
    -X POST -H 'Content-Type:application/json'
    -d '{"uid":"{{ superuser_username }}","password":"{{ superuser_password_hash }}"}'
    https://{{ groups['masters'][0] }}/acs/api/v1/auth/login
    --cacert {{ cacert_destination_file }}
  args:
    warn: False
  register: token

- set_fact:
    token_resp: "{{ token.stdout|from_json }}"

- debug: var=token_resp